name: Pull Request Test Senzing Yum Build on Debian

on:
  pull_request:
    branches:
      - issue-22.mahchiahui.1

jobs:
  prBuildSenzingYum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download And Install Senzing Deb Package Onto Runner
        id: download_install_senzing_deb
        env:
          SENZING_REPO_URL: https://senzing-staging-apt.s3.amazonaws.com/senzingstagingrepo_1.0.0-1_amd64.deb
        run: |
          wget ${SENZING_REPO_URL} >> output.log 2>&1
          sudo apt-get -y install ./${SENZING_REPO_URL##*/} >> output.log 2>&1
          rm -rf senzingrepo_1.0.0-1_amd64.deb >> output.log 2>&1
          sudo apt-get update -y >> output.log 2>&1
      - name: Docker build Senzing Yum
        id: build_senzing_yum
        run: |
          docker build /this_should_not_work/ >> build_failure.log 2>&1
          cat build_failure.log >> output.log 2>&1
      - name: Slack Notification
        id: slack_notification
        uses: Senzing/git-action-slack-notification@1.0.0
        if: failure()
        env:
          SLACK_CHANNEL: ci-cd-dev
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: 'Failed to build Debian version on GitHub Commit SHA ${{ github.sha }}'
          SLACK_MESSAGE: |
            Failed to build on GitHub Commit SHA ${{ github.sha }}
            Git Issue URL: ${{ steps.create_git_issue.outputs.git_issue_url }}
          SLACK_USERNAME: docker-yum
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
      - name: Persisting log
        id: persisting_log
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: workflow_log
          path: output.log